/*
 * Transportation Cost Management API
 *
 * Movie site OPENAPI
 *
 * API version: 1.0.0
 * Contact: jjunary4471@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorResponse struct {

	// 에러 코드
	ErrorCode string `json:"errorCode,omitempty"`

	// 에러 메세지
	ErrorMessage string `json:"errorMessage,omitempty"`
}
