/*
 * Transportation Cost Management API
 *
 * Movie site OPENAPI
 *
 * API version: 1.0.0
 * Contact: jjunary4471@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MovieInfo struct {
	MovieName string `json:"movieName,omitempty"`

	Details string `json:"details,omitempty"`
}
