/*
 * Transportation Cost Management API
 *
 * Movie site OPENAPI
 *
 * API version: 1.0.0
 * Contact: jjunary4471@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FavoriteResponse struct {
	UserId string `json:"userId"`

	Date string `json:"date"`

	Favorite []MovieInfo `json:"favorite"`
}

type MoviesResponse struct {
	UserId string `json:"userId"`

	Date string `json:"date"`

	SearchMovies []MovieInfo `json:"searchMovies"`
}

type MovieResponse struct {
	UserId string `json:"userId"`

	Date string `json:"date"`

	Movie MovieInfo `json:"movie"`
}
