/*
 * Transportation Cost Management API
 *
 * Movie site OPENAPI
 *
 * API version: 1.0.0
 * Contact: jjunary4471@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// RegisterFavorite
func RegisterFavorite(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SearchFavorite
func SearchFavorite(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
